---
regions:   # nuke 실행 리전 기입
- "global" # global 리소스 전용 
- "ap-northwest-1"
- "us-west-1"
account-blocklist: # nuke 블랙리스트 AWS ID
- 1234567890

# 리소스 타겟 또는 제외
resource-types:   # targets - 타겟 / excludes - 제외
	targets:
  - S3Bucket
	excludes:
  - IAMUser
  - IAMUserPolicyAttachment
  - IAMUserAccessKey


# nuke 진행할 AWS ID
accounts:        
  555133742:
    filters:   # 삭제 대상 리소스 필터
      IAMUser:
      - "admin"
      IAMUserPolicyAttachment:
      - property: RoleName
        value: "admin"
      IAMUserAccessKey:
      - property: UserName
        value: "admin"
      S3Bucket:
      - "s3://my-bucket"
 