name: Run aws-nuke

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  aws_nuke:
    runs-on: ubuntu-latest
    container:
      image: quay.io/rebuy/aws-nuke:v2.16.0
      options: --user root
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      # Configure AWS Credentials step는 없어도 무방하거나,
      # 남겨 두려면 아래처럼 env 전달 추가해줘야 함
      # 하지만 aws-nuke 쓸 땐 주로 직접 env 지정하는 게 더 명확함

      - name: run aws-nuke
        run: aws-nuke -c config.yml --force --no-dry-run --force-sleep 3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-northeast-2

